<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
		<TargetFrameworks>net8.0;net9.0</TargetFrameworks>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AspNetCore.HealthChecks.Kafka" Version="8.0.1" />
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.3" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.3" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.3" />

      <PackageReference Include="KafkaFlow.LogHandler.Microsoft" Version="4.1.0" />
      <PackageReference Include="KafkaFlow.LogHandler.Console" Version="4.1.0" />
      <PackageReference Include="KafkaFlow.Admin" Version="4.1.0" />
      <PackageReference Include="KafkaFlow.Admin.WebApi" Version="4.1.0" />
      <PackageReference Include="KafkaFlow.Admin.Dashboard" Version="4.1.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Concurrent.Kafka.Core\Concurrent.Kafka.Core.csproj" />
    </ItemGroup>

</Project>
